version: '3.8'

services:
  sut:
    build: ./result/tests/
    image: eltitans/sut:latest
    depends_on:
      - vote
      - result
      - worker
    networks:
      - front-tier

  vote:
    build: ./vote/
    image: eltitans/vote:latest
    ports: ["80"]
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result/
    image: eltitans/result:latest
    ports: ["80"]
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  worker:
    build: ./worker/
    image: eltitans/worker:latest
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  redis:
    image: redis:alpine
    networks:
      - back-tier

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
