kind: Service
apiVersion: v1
metadata:
  name:  redis
spec:
  selector:
    app:  redis
  type:  ClusterIP        #  LoadBalancer | ClusterIP | NodePort
  ports:
  - name:  redis
    port:  6379
    targetPort:  6379