kind: Service
apiVersion: v1
metadata:
  name:  db
spec:
  selector:
    app:  postgres
  type:  ClusterIP        #  LoadBalancer | ClusterIP | NodePort
  ports:
  - name:  db
    port:  5432
    targetPort:  5432